/**
 * withHealthKitBridge.js
 *
 * Config plugin that injects a standard React Native NativeModule (RCT_EXTERN_MODULE)
 * for HealthKit directly into the Xcode project during `expo prebuild`.
 *
 * This approach is 100% reliable because:
 *  - The Swift/ObjC files are written to ios/EstouBem/ as part of prebuild
 *  - They're added to the Xcode Sources build phase via xcode-project API
 *  - No dependency on ExpoModulesProvider.swift autolinking
 *  - NativeModules.EstouBemHealthKit is always available in JS on iOS
 */

const { withXcodeProject, withDangerousMods } = require("@expo/config-plugins");
const path = require("path");
const fs = require("fs");

// ── Swift implementation ──────────────────────────────────────────────────────

const HEALTHKIT_BRIDGE_SWIFT = `//
//  HealthKitBridge.swift — generated by plugins/withHealthKitBridge.js
//
import Foundation
import HealthKit

@objc(EstouBemHealthKit)
class EstouBemHealthKit: NSObject {

  private let store = HKHealthStore()

  @objc static func requiresMainQueueSetup() -> Bool { false }

  @objc func isAvailable(
    _ resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    resolve(HKHealthStore.isHealthDataAvailable())
  }

  @objc func requestAuthorization(
    _ resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    var read = Set<HKObjectType>()
    if let t = HKObjectType.quantityType(forIdentifier: .heartRate)             { read.insert(t) }
    if let t = HKObjectType.quantityType(forIdentifier: .stepCount)             { read.insert(t) }
    if let t = HKObjectType.quantityType(forIdentifier: .oxygenSaturation)      { read.insert(t) }
    if let t = HKObjectType.quantityType(forIdentifier: .bloodPressureSystolic) { read.insert(t) }
    if let t = HKObjectType.quantityType(forIdentifier: .bloodPressureDiastolic){ read.insert(t) }
    if let t = HKObjectType.categoryType(forIdentifier: .sleepAnalysis)         { read.insert(t) }
    if let t = HKObjectType.quantityType(forIdentifier: .activeEnergyBurned)    { read.insert(t) }
    store.requestAuthorization(toShare: nil, read: read) { ok, err in
      if let err = err { reject("HK_AUTH", err.localizedDescription, err) }
      else { resolve(ok) }
    }
  }

  @objc func getHeartRate(
    _ resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    queryLatest(.heartRate, unit: HKUnit(from: "count/min"), hoursBack: 720, resolve: resolve)
  }

  @objc func getStepCount(
    _ resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    guard let type = HKQuantityType.quantityType(forIdentifier: .stepCount) else { resolve(0); return }
    let start = Calendar.current.startOfDay(for: Date())
    let pred = HKQuery.predicateForSamples(withStart: start, end: Date(), options: .strictStartDate)
    let q = HKStatisticsQuery(quantityType: type, quantitySamplePredicate: pred, options: .cumulativeSum) { _, stats, _ in
      resolve(Int(stats?.sumQuantity()?.doubleValue(for: .count()) ?? 0))
    }
    store.execute(q)
  }

  @objc func getBloodOxygen(
    _ resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    queryLatest(.oxygenSaturation, unit: .percent(), hoursBack: 720, multiplyBy: 100, resolve: resolve)
  }

  @objc func getSleepHours(
    _ resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    guard let type = HKObjectType.categoryType(forIdentifier: .sleepAnalysis) else { resolve(nil); return }
    guard let start = Calendar.current.date(byAdding: .hour, value: -36, to: Date()) else { resolve(nil); return }
    let pred = HKQuery.predicateForSamples(withStart: start, end: Date(), options: .strictStartDate)
    let sort = NSSortDescriptor(key: HKSampleSortIdentifierEndDate, ascending: false)
    let q = HKSampleQuery(sampleType: type, predicate: pred, limit: HKObjectQueryNoLimit, sortDescriptors: [sort]) { _, samples, _ in
      guard let cats = samples as? [HKCategorySample] else { resolve(nil); return }
      var total: TimeInterval = 0
      for s in cats {
        var sleeping = false
        if #available(iOS 16.0, *) {
          sleeping = s.value == HKCategoryValueSleepAnalysis.asleepCore.rawValue
                  || s.value == HKCategoryValueSleepAnalysis.asleepDeep.rawValue
                  || s.value == HKCategoryValueSleepAnalysis.asleepREM.rawValue
                  || s.value == HKCategoryValueSleepAnalysis.asleepUnspecified.rawValue
        } else {
          sleeping = s.value == HKCategoryValueSleepAnalysis.asleep.rawValue
        }
        if sleeping { total += s.endDate.timeIntervalSince(s.startDate) }
      }
      resolve(total > 0 ? round((total / 3600) * 10) / 10 : nil)
    }
    store.execute(q)
  }

  @objc func getBloodPressure(
    _ resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    guard let sysType = HKSampleType.quantityType(forIdentifier: .bloodPressureSystolic) else { resolve(nil); return }
    guard let start = Calendar.current.date(byAdding: .hour, value: -720, to: Date()) else { resolve(nil); return }
    let pred = HKQuery.predicateForSamples(withStart: start, end: Date(), options: .strictStartDate)
    let sort = NSSortDescriptor(key: HKSampleSortIdentifierEndDate, ascending: false)
    let mmHg = HKUnit.millimeterOfMercury()
    let q = HKSampleQuery(sampleType: sysType, predicate: pred, limit: 1, sortDescriptors: [sort]) { [weak self] _, samples, _ in
      guard let self = self, let sys = samples?.first as? HKQuantitySample else { resolve(nil); return }
      let systolic = Int(sys.quantity.doubleValue(for: mmHg))
      guard let diaType = HKSampleType.quantityType(forIdentifier: .bloodPressureDiastolic) else {
        resolve(["systolic": systolic, "diastolic": 0]); return
      }
      let dq = HKSampleQuery(sampleType: diaType, predicate: pred, limit: 1, sortDescriptors: [sort]) { _, dias, _ in
        let diastolic = (dias?.first as? HKQuantitySample).map { Int($0.quantity.doubleValue(for: mmHg)) } ?? 0
        resolve(["systolic": systolic, "diastolic": diastolic])
      }
      self.store.execute(dq)
    }
    store.execute(q)
  }

  @objc func getActiveCalories(
    _ resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    guard let type = HKQuantityType.quantityType(forIdentifier: .activeEnergyBurned) else { resolve(0); return }
    let start = Calendar.current.startOfDay(for: Date())
    let pred = HKQuery.predicateForSamples(withStart: start, end: Date(), options: .strictStartDate)
    let q = HKStatisticsQuery(quantityType: type, quantitySamplePredicate: pred, options: .cumulativeSum) { _, stats, _ in
      resolve(Int(stats?.sumQuantity()?.doubleValue(for: .kilocalorie()) ?? 0))
    }
    store.execute(q)
  }

  private func queryLatest(
    _ id: HKQuantityTypeIdentifier,
    unit: HKUnit,
    hoursBack: Int,
    multiplyBy: Double = 1,
    resolve: @escaping RCTPromiseResolveBlock
  ) {
    guard let type = HKSampleType.quantityType(forIdentifier: id) else { resolve(nil); return }
    guard let start = Calendar.current.date(byAdding: .hour, value: -hoursBack, to: Date()) else { resolve(nil); return }
    let pred = HKQuery.predicateForSamples(withStart: start, end: Date(), options: .strictStartDate)
    let sort = NSSortDescriptor(key: HKSampleSortIdentifierEndDate, ascending: false)
    let q = HKSampleQuery(sampleType: type, predicate: pred, limit: 1, sortDescriptors: [sort]) { _, samples, _ in
      guard let s = samples?.first as? HKQuantitySample else { resolve(nil); return }
      resolve(round(s.quantity.doubleValue(for: unit) * multiplyBy * 10) / 10)
    }
    store.execute(q)
  }
}
`;

// ── ObjC bridge ───────────────────────────────────────────────────────────────

const HEALTHKIT_BRIDGE_OBJC = `//
//  HealthKitBridge.m — generated by plugins/withHealthKitBridge.js
//
#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(EstouBemHealthKit, NSObject)
RCT_EXTERN_METHOD(isAvailable:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(requestAuthorization:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(getHeartRate:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(getStepCount:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(getBloodOxygen:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(getSleepHours:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(getBloodPressure:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(getActiveCalories:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
@end
`;

// ── Plugin ────────────────────────────────────────────────────────────────────

function withHealthKitBridge(config) {
  // 1. Write the source files into ios/EstouBem/ during prebuild
  config = withDangerousMods(config, [
    "ios",
    (config) => {
      const iosRoot = config.modRequest.platformProjectRoot;
      const appDir = path.join(iosRoot, "EstouBem");

      if (!fs.existsSync(appDir)) fs.mkdirSync(appDir, { recursive: true });

      fs.writeFileSync(path.join(appDir, "HealthKitBridge.swift"), HEALTHKIT_BRIDGE_SWIFT, "utf8");
      fs.writeFileSync(path.join(appDir, "HealthKitBridge.m"),     HEALTHKIT_BRIDGE_OBJC,  "utf8");

      // Ensure bridging header imports React so Swift can use RCTPromiseResolveBlock
      const bridgingHeader = path.join(appDir, "EstouBem-Bridging-Header.h");
      if (fs.existsSync(bridgingHeader)) {
        let content = fs.readFileSync(bridgingHeader, "utf8");
        if (!content.includes("RCTBridgeModule")) {
          content += "\n#import <React/RCTBridgeModule.h>\n";
          fs.writeFileSync(bridgingHeader, content, "utf8");
        }
      }

      console.log("[withHealthKitBridge] Wrote HealthKitBridge.swift + HealthKitBridge.m");
      return config;
    },
  ]);

  // 2. Add both files to the Xcode project Sources build phase
  config = withXcodeProject(config, (config) => {
    const project = config.modResults;

    // addSourceFile(filePath, opts, groupName) — adds to default target
    const swiftFile = project.addSourceFile(
      "EstouBem/HealthKitBridge.swift",
      { target: project.getFirstTarget().uuid },
    );
    const objcFile = project.addSourceFile(
      "EstouBem/HealthKitBridge.m",
      { target: project.getFirstTarget().uuid },
    );

    console.log("[withHealthKitBridge] Added to Xcode project:", swiftFile, objcFile);
    return config;
  });

  return config;
}

module.exports = withHealthKitBridge;
